#Identify stocks where the news sentiment is extremely optimistic (>0.7) but the stock price hasn’t risen much—or has even fallen
SELECT 
    n.ticker_symbol,
    s.sentiment_score,
    m.open_price,
    m.close_price,
    ((m.close_price - m.open_price) / m.open_price * 100) AS intraday_return
FROM News n
JOIN NewsSentiment s ON n.news_id = s.news_id
JOIN MarketData m ON n.ticker_symbol = m.ticker_symbol 
    AND n.publish_time::date = m.trade_date
WHERE s.sentiment_score > 0.7
  AND m.close_price <= m.open_price
ORDER BY s.sentiment_score DESC;

#Track the number of news stories generated by each sector today, along with the sector’s average sentiment score. This helps users quickly identify the hottest sectors right now.
  SELECT 
    a.sector,
    COUNT(n.news_id) AS news_count,
    ROUND(AVG(s.sentiment_score), 2) AS avg_sector_sentiment
FROM Assets a
JOIN News n ON a.ticker_symbol = n.ticker_symbol
JOIN NewsSentiment s ON n.news_id = s.news_id
GROUP BY a.sector
ORDER BY news_count DESC;

#For a specific user, determine the sentiment of the most recent news article among all the stocks they are following
SELECT DISTINCT ON (w.ticker_symbol)
    w.user_name,
    w.ticker_symbol,
    n.title,
    s.sentiment_score,
    n.publish_time
FROM Watchlist w
JOIN News n ON w.ticker_symbol = n.ticker_symbol
JOIN NewsSentiment s ON n.news_id = s.news_id
WHERE w.user_name = 'erer'
ORDER BY w.ticker_symbol, n.publish_time DESC; -- 获取每个股票最新的一条新闻

#List all stocks for which a CRITICAL-level alert has been triggered, and display the headlines of the news stories that triggered the alert.
  SELECT 
    al.created_at,
    n.ticker_symbol,
    al.alert_level,
    al.message,
    n.title
FROM Alerts al
JOIN News n ON al.news_id = n.news_id
WHERE al.alert_level = 'CRITICAL'
ORDER BY al.created_at DESC;

#Check the latest 10 news articles and their matched stock price
SELECT n.ticker_symbol,n.title,s.sentiment_score,m.close_price,m.open_price
FROM news n left join NewsSentiment s on n.news_id=s.news_id
left join MarketData m on n.ticker_symbol=m.ticker_symbol 
and n.publish_time::date=m.trade_date
order by n.publish_time desc
limit 10;

#Semantic Search and Vector Databases
WITH target_news AS (
    SELECT news_id, title, ticker_symbol
    FROM News 
    WHERE title ILIKE '%AI%' -- 找到目标
    ORDER BY publish_time DESC 
    LIMIT 1
)

SELECT 
    n.ticker_symbol, 
    n.title, 
    (ne.embedding <=> (SELECT embedding FROM NewsEmbeddings WHERE news_id = (SELECT news_id FROM target_news))) AS semantic_distance
FROM News n
JOIN NewsEmbeddings ne ON n.news_id = ne.news_id
WHERE n.news_id != (SELECT news_id FROM target_news)
ORDER BY semantic_distance ASC
LIMIT 5;

#Identify stocks for which news sentiment has suddenly shifted from negative (<-0.3) to positive (>0.5) within the past two days.
SELECT 
    n1.ticker_symbol,
    s1.sentiment_score AS old_sentiment,
    s2.sentiment_score AS new_sentiment,
    (s2.sentiment_score - s1.sentiment_score) AS sentiment_swing
FROM News n1
JOIN NewsSentiment s1 ON n1.news_id = s1.news_id
JOIN News n2 ON n1.ticker_symbol = n2.ticker_symbol
JOIN NewsSentiment s2 ON n2.news_id = s2.news_id
WHERE n1.publish_time < n2.publish_time 
  AND n1.publish_time >= NOW() - INTERVAL '2 days'
  AND s1.sentiment_score < -0.3 
  AND s2.sentiment_score > 0.5
ORDER BY sentiment_swing DESC;


#Identify stocks whose news volume has suddenly surged (for example, to more than 1.5 times the average news volume over the past 7 days)
WITH daily_counts AS (
    SELECT ticker_symbol, COUNT(*) as cnt
    FROM News
    WHERE publish_time >= NOW() - INTERVAL '1 day'
    GROUP BY ticker_symbol
),
avg_counts AS (
    SELECT ticker_symbol, 
        COUNT(*) / GREATEST(1, LEAST(7, CURRENT_DATE - MIN(publish_time)::date + 1))::numeric AS avg_cnt
    FROM News
    WHERE publish_time >= NOW() - INTERVAL '7 days'
    GROUP BY ticker_symbol
)
SELECT d.ticker_symbol, d.cnt as today_count, ROUND(a.avg_cnt, 2) as week_avg
FROM daily_counts d
JOIN avg_counts a ON d.ticker_symbol = a.ticker_symbol
WHERE d.cnt > a.avg_cnt * 1.5 
ORDER BY d.cnt DESC;

#For a specific user, list all assets in their watchlist that have a “severe negative warning” and calculate the user's current level of risk exposure.
SELECT 
    w.user_name,
    w.ticker_symbol,
    COUNT(al.alert_id) AS critical_alerts_count,
    MAX(al.created_at) AS last_alert_time
FROM Watchlist w
JOIN News n ON w.ticker_symbol = n.ticker_symbol
JOIN Alerts al ON n.news_id = al.news_id
WHERE w.user_name = 'erer' 
  AND al.alert_level = 'CRITICAL'
GROUP BY w.user_name, w.ticker_symbol
ORDER BY critical_alerts_count DESC;
